- name: Execute cold standby remediation
  hosts: hypervisor
  gather_facts: false
  become: true

  tasks: 
    - name: Start backup LXC
      ansible.builtin.command:
        cmd: "pct start 112"

    - name: Verify LXC running state
      ansible.builtin.command:
        cmd: "pct status 112"
      register: lxc_status
      until: "'status: running' in lxc_status.stdout"
      retries: 100
      delay: 0.1
      changed_when: false
