---
- name: Stop cumulative Packet Loss measurement
  hosts: source
  become: yes 
  gather_facts: false
  
  vars:
    state_file: "/home/user/state/run_state.json"
    log_dir_local: "/home/user/logs"

  tasks:
    - name: Read state
      slurp:
        src: "{{ state_file }}"
      register: slurped_state

    - name: Parse state
      set_fact:
        ping_state: "{{ (slurped_state['content'] | b64decode) | from_json }}"

    - name: SIGINT ping
      shell: "kill -2 {{ ping_state.pid }}"
      ignore_errors: yes # In case this doesn't work, killall.yaml will end ping

    - name: Pull runs log
      fetch:
        src: "{{ ping_state.logfile_path }}"
        dest: "{{ log_dir_local }}/{{ ping_state.logfile_name }}"
        flat: yes

    - name: reset state file
      file:
        path: "{{ state_file }}"
        state: absent