network:
  version: 2
  renderer: networkd
  ethernets:

    #-----------------------#
    #       TARGET          #
    #-----------------------#

    # MANAGEMENT PLANE
    # vmbr99
    ens18:
      addresses:
        - 192.168.99.10/24

    # SERVICE PLANE 
    # vmbr88
    ens19:
      addresses:
        - 10.254.0.10/24
      routes:
        - to: default
          via: 10.254.0.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

    # DATA PLANE
    # vmbr1 - Shared Target Subnet
    ens20:
      addresses:
        - 10.0.1.10/24
      routes:
        - to: 10.0.0.0/16    # All DATA PLANE Networks
          via: 10.0.1.110    # Via DATA PLANE Target Edge
