network:
  version: 2
  renderer: networkd
  ethernets:

    #-----------------------#
    #       TRANSIT 2       #
    #-----------------------#

    # MANAGEMENT PLANE
    # vmbr99
    ens18:
      addresses:
        - 192.168.99.130/24

    # SERVICE PLANE
    # vmbr88
    ens19:
      addresses:
        - 10.254.0.130/24
      routes:
        - to: default
          via: 10.254.0.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]

    # DATA PLANE
    # vmbr3 
    # Transit 2 - Target Edge
    ens20:
      addresses: [10.0.20.130/24]

    # DATA PLANE
    # vmbr6
    # Transit 2 - Source Edge
    ens21:
      addresses: [10.0.50.130/24]
